config/routes.rb
Rails.application.routes.draw do
  
  root 'radnom_apps#index'
  resources :radnom_apps
  get '/wheel' => 'radnom_apps#wheel'
  get '/list' => 'radnom_apps#list'

end

app/models/radnom_app.rb
class RadnomApp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/radnom_apps_controller.rb
class RadnomAppsController < ApplicationController
  before_action :set_radnom_app, only: [:show, :edit, :update, :destroy]

  # GET /radnom_apps
  # GET /radnom_apps.json
  def index
  end

  def wheel
    @radnom_apps = RadnomApp.all
  end

  def list
    @radnom_apps = RadnomApp.all
  end

  # GET /radnom_apps/1
  # GET /radnom_apps/1.json
  def show
  end

  # GET /radnom_apps/new
  def new
    @radnom_app = RadnomApp.new
  end

  # GET /radnom_apps/1/edit
  def edit
  end

  # POST /radnom_apps
  # POST /radnom_apps.json
  def create
    @radnom_app = RadnomApp.new(radnom_app_params)

    respond_to do |format|
      if @radnom_app.save
        format.html { redirect_to @radnom_app, notice: 'Ah yeah!' }
        format.json { render :show, status: :created, location: @radnom_app }
      else
        format.html { render :new }
        format.json { render json: @radnom_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /radnom_apps/1
  # PATCH/PUT /radnom_apps/1.json
  def update
    respond_to do |format|
      if @radnom_app.update(radnom_app_params)
        format.html { redirect_to @radnom_app, notice: 'Oh, I can def see them being chosen...' }
        format.json { render :show, status: :ok, location: @radnom_app }
      else
        format.html { render :edit }
        format.json { render json: @radnom_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /radnom_apps/1
  # DELETE /radnom_apps/1.json
  def destroy
    @radnom_app.destroy
    respond_to do |format|
      format.html { redirect_to radnom_apps_url, notice: 'Radnom app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_radnom_app
      @radnom_app = RadnomApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def radnom_app_params
      params.require(:radnom_app).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/radnom_apps_helper.rb
module RadnomAppsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <br>
  <title>Radnom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Exo+2:900' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= yield %>

</body>
</html>

app/views/radnom_apps/_form.html.erb
<%= form_for(@radnom_app) do |f| %>
  <% if @radnom_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@radnom_app.errors.count, "error") %> prohibited this radnom_app from being saved:</h2>

      <ul>
      <% @radnom_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/radnom_apps/edit.html.erb
<div class="edit_form">
<h1>Edit that name!</h1>
<br>

<%= render 'form' %>
</div>

<div class="form_buttons">
<%= link_to 'Show', @radnom_app %> |
<%= link_to 'Back', list_path %>
</div>

app/views/radnom_apps/index.html.erb
<p id="notice"><%= notice %></p>

<div class="index_header">
  <h1>Radnom</h1>
</div>

<div class="index_spin_button">
  <a href="/wheel" title="Spin The Wheel!">Spin the Radnomizer!</a>
</div>

<!-- <div class="attribution">
<h5>By Findlay Parke, with credit to André Cortellini!</h5>
</div> -->

app/views/radnom_apps/list.html.erb
<div class="form">
  <table>
    <thead>
      <tr>
        <th>Names</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @radnom_apps.each do |radnom_app| %>
        <tr>
          <td><%= radnom_app.name %></td>
<!--           <td><%= link_to 'Show', radnom_app %></td> -->
          <td><%= link_to 'Edit', edit_radnom_app_path(radnom_app) %></td>
<!--           <td><%= link_to 'Destroy', radnom_app, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="form_buttons">
<!--   <%= link_to 'Add name', new_radnom_app_path %>
  <br> -->
  <%= link_to 'Back to the wheel!', wheel_path %>
</div>

app/views/radnom_apps/new.html.erb
<h1>New Entry</h1>

<br>

<%= render 'form' %>

<%= link_to 'Back', radnom_apps_path %>

app/views/radnom_apps/show.html.erb
<div class="show_value">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @radnom_app.name %>
</p>


<%= link_to 'Edit', edit_radnom_app_path(@radnom_app) %> |
<%= link_to 'Back', list_path %>

</div>

app/views/radnom_apps/wheel.html.erb
<div id="wrapper">
            
        <div id="wheel">
            <div id="inner-wheel">
            <% @radnom_apps.each do |radnom_app| %>
                <div class="sec"><span class="wheel_value"><%= radnom_app.name %></span></div>
<!--                 <div class="sec"><span class="wheel_value">Dave</span></div>
                <div class="sec"><span class="wheel_value">Marc</span></div>
                <div class="sec"><span class="wheel_value">Jen</span></div>
                <div class="sec"><span class="wheel_value">Fin</span></div>
                <div class="sec"><span class="wheel_value">Thomas</span></div> -->
                <% end %>
            </div>       
           
            <div id="spin">
                <div id="inner-spin"></div>
            </div>
            
            <div id="shine"></div>
        </div>
        
        
        <!-- <div id="txt"></div> -->
  </div>

  <div class="buttons">
<a href="/list" title="Change the wheel values">Change the values</a>
<br>
<a href="/" title="Back that ass up">Back to the main menu</a>
</div>


<!-- <div class="back_to_menu_button">

</div>
 -->